### ISSUE TITLE
local video not show in janus video room

### ISSUE THREAD

**Issue by fukemy** [crossle/janus-gateway-ios#12]
Hello, today i checked again about local video, i saw this is not display in janus video room event the debug "setlocaldescription" is fired.
 I tried to download your project again and run, then the local video still not display in janus, only display in my phone.

![Screen Shot 2020-04-16 at 16 01 32](https://user-images.githubusercontent.com/8202437/79436807-8c903000-7ffb-11ea-8f8d-9b92eee7ee2b.png)

Below image is my phone screen: 
![IMG_0031](https://user-images.githubusercontent.com/8202437/79436955-bcd7ce80-7ffb-11ea-89b6-333d0a527077.PNG)

**Comment by crossle** [comment]
If you input turn server?

**Comment by fukemy** [comment]
i tried to remote turn server then set my default turn server, nothing working 
![Screen Shot 2020-04-16 at 16 18 00](https://user-images.githubusercontent.com/8202437/79438611-f3aee400-7ffd-11ea-8694-72924bd2c517.png)

**Comment by fukemy** [comment]
im so sorry, your project is show normally local videoview in Janus videoroom, only my project not show :(, i dont know why, i just change your ViewController to swift zz, trying to find problem now.

**Comment by crossle** [comment]
Good luck

**Comment by fukemy** [comment]
solved it, because of NAT problem
