### ISSUE TITLE
new janus update, now the subscriber now only show black screen event sdp is paired

### ISSUE THREAD

**Issue by fukemy** [crossle/janus-gateway-ios#13]
hi, can you test with your project again? it's suddenly not working more after janus have new build.
As the test im using:

```
NSURL *url = [[NSURL alloc] initWithString:@"wss://janus.conf.meetecho.com/ws"];
```

and set turn server is empty.

When running i saw this log:
```

2020-06-24 15:35:47.843586+0700 janus-gateway-ios[5903:2189329] =========didAddStream
2020-06-24 15:35:47.940033+0700 janus-gateway-ios[5903:2189299] Metal API Validation Enabled
2020-06-24 15:35:48.926340+0700 janus-gateway-ios[5903:2189299] ====onMessage={
   "janus": "ack",
   "session_id": 2652385476778308,
   "transaction": "vFNMOUVbJl7Z"
}
2020-06-24 15:35:48.927229+0700 janus-gateway-ios[5903:2189299] Just an ack
2020-06-24 15:35:48.927815+0700 janus-gateway-ios[5903:2189299] ====onMessage={
   "janus": "event",
   "session_id": 2652385476778308,
   "transaction": "vFNMOUVbJl7Z",
   "sender": 236944681777638,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "event",
         "room": 1234,
         "started": "ok"
      }
   }
}
```, but i did not see the Streaming plugin start relaying media..., so it's only have black screen

**Comment by fukemy** [comment]
as the update, the publisher can not send it video to videoroom( im using your code, it not working more)
![Screen Shot 2020-06-24 at 15 57 21](https://user-images.githubusercontent.com/8202437/85525581-68705100-b633-11ea-99e0-578091d92905.png)
im REALLY need your help, thanks

**Comment by fukemy** [comment]
hi, after check i got this log:
```

2020-07-06 10:14:25.638904+0700 Link[1203:614554] ====onMessage={
   "janus": "event",
   "session_id": 8505352496515682,
   "transaction": "uM38u09fWSns",
   "sender": 5501217376149289,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "attached",
         "room": 580620017271,
         "id": 8560356790080109,
         "display": "7c788e5c-0c74-4264-a7b3-68ae6a6f5499_zS9wqFEuZsPKGp4LDDpNpw_1594004320546"
      }
   },
   "jsep": {
      "type": "offer",
      "sdp": "v=0\r\no=- 1594004322080109 1 IN IP4 115.165.166.229\r\ns=VideoRoom 580620017271\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS janus\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 115.165.166.229\r\na=sendonly\r\na=mid:audio\r\na=rtcp-mux\r\na=ice-ufrag:NHej\r\na=ice-pwd:CgnS3EyCuixNzZ7W6b77kh\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5F:22:62:91:6A:2A:73:EB:56:36:58:A4:2F:5F:47:C7:C5:AD:15:C8:A8:7C:3E:41:97:66:EC:91:91:CA:1F:5E\r\na=setup:actpass\r\na=rtpmap:111 opus/48000/2\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=rtcp-fb:111 transport-cc\r\na=msid:janus janusa0\r\na=ssrc:322308754 cname:janus\r\na=ssrc:322308754 msid:janus janusa0\r\na=ssrc:322308754 mslabel:janus\r\na=ssrc:322308754 label:janusa0\r\na=candidate:1 1 udp 2013266431 115.165.166.229 35991 typ host\r\na=candidate:2 1 udp 2013266430 172.17.0.1 49151 typ host\r\na=candidate:3 1 udp 2013266429 172.18.0.1 58067 typ host\r\na=candidate:4 1 udp 2013266428 172.16.0.1 55113 typ host\r\na=candidate:5 1 udp 2013266427 10.0.0.1 37904 typ host\r\na=end-of-candidates\r\nm=video 9 UDP/TLS/RTP/SAVPF 107 108\r\nc=IN IP4 115.165.166.229\r\na=sendonly\r\na=mid:video\r\na=rtcp-mux\r\na=ice-ufrag:NHej\r\na=ice-pwd:CgnS3EyCuixNzZ7W6b77kh\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5F:22:62:91:6A:2A:73:EB:56:36:58:A4:2F:5F:47:C7:C5:AD:15:C8:A8:7C:3E:41:97:66:EC:91:91:CA:1F:5E\r\na=setup:actpass\r\na=rtpmap:107 H264/90000\r\na=rtcp-fb:107 ccm fir\r\na=rtcp-fb:107 nack\r\na=rtcp-fb:107 nack pli\r\na=rtcp-fb:107 goog-remb\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:13 urn:3gpp:video-orientation\r\na=fmtp:107 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:108 rtx/90000\r\na=fmtp:108 apt=107\r\na=ssrc-group:FID 2712901041 834959026\r\na=msid:janus janusv0\r\na=ssrc:2712901041 cname:janus\r\na=ssrc:2712901041 msid:janus janusv0\r\na=ssrc:2712901041 mslabel:janus\r\na=ssrc:2712901041 label:janusv0\r\na=ssrc:834959026 cname:janus\r\na=ssrc:834959026 msid:janus janusv0\r\na=ssrc:834959026 mslabel:janus\r\na=ssrc:834959026 label:janusv0\r\na=candidate:1 1 udp 2013266431 115.165.166.229 35991 typ host\r\na=candidate:2 1 udp 2013266430 172.17.0.1 49151 typ host\r\na=candidate:3 1 udp 2013266429 172.18.0.1 58067 typ host\r\na=candidate:4 1 udp 2013266428 172.16.0.1 55113 typ host\r\na=candidate:5 1 udp 2013266427 10.0.0.1 37904 typ host\r\na=end-of-candidates\r\n"
   }
}
peerConnection setRemoteDescription error: Optional(Error Domain=org.webrtc.RTCPeerConnection Code=-1 "Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters.." UserInfo={NSLocalizedDescription=Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..})
```
Do you know what's wrong with my sdp?

**Comment by crossle** [comment]
group:BUNDLE ?  need setup PeerConnection MAXBUNDLE ?

**Comment by fukemy** [comment]
hmm i dont know much about sdp, i only used your project to run, but i only fix the profile-level-id to 42e01f -> this make my project can get the video from janus room, the problem is can not publish video to server

```
+ (RTCSessionDescription *)descriptionFromJSONDictionary:
    (NSDictionary *)dictionary {
    NSString *typeString = dictionary[kRTCSessionDescriptionTypeKey];
    RTCSdpType type = [[self class] typeForString:typeString];
    NSString *sdp = dictionary[kRTCSessionDescriptionSdpKey];
        sdp = [sdp stringByReplacingOccurrencesOfString:@"42001f" withString:@"42e01f"];
    return [[RTCSessionDescription alloc] initWithType:type sdp:sdp];
}
```,
im so sorry for my silly question, but im stuck in 2 weeks T^T , here is log i got from publisherConnection after offer for default media constraint:
```
publisherPeerConnection sdp: v=0

o=- 8172565763379018011 2 IN IP4 127.0.0.1

s=-

t=0 0

a=group:BUNDLE audio video

a=msid-semantic: WMS ARDAMS

m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=ice-ufrag:N5UE

a=ice-pwd:/1ZUr+/LodAe2Let3amFS29C

a=ice-options:trickle renomination

a=fingerprint:sha-256 EE:15:E8:D6:ED:98:3C:BD:36:C3:C3:A7:98:E8:29:4F:B6:FF:8B:0E:E9:A7:C3:0F:E4:1B:03:A6:1B:CD:81:84

a=setup:actpass

a=mid:audio

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=sendrecv

a=rtcp-mux

a=rtpmap:111 opus/48000/2

a=rtcp-fb:111 transport-cc

a=fmtp:111 minptime=10;useinbandfec=1

a=rtpmap:103 ISAC/16000

a=rtpmap:104 ISAC/32000

a=rtpmap:9 G722/8000

a=rtpmap:102 ILBC/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:106 CN/32000

a=rtpmap:105 CN/16000

a=rtpmap:13 CN/8000

a=rtpmap:110 telephone-event/48000

a=rtpmap:112 telephone-event/32000

a=rtpmap:113 telephone-event/16000

a=rtpmap:126 telephone-event/8000

a=ssrc:736889125 cname:FBZNwDVqGrEC/n5L

a=ssrc:736889125 msid:ARDAMS 7b90022d-8bce-4540-b5e9-004e264f2469

a=ssrc:736889125 mslabel:ARDAMS

a=ssrc:736889125 label:7b90022d-8bce-4540-b5e9-004e264f2469

m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=ice-ufrag:N5UE

a=ice-pwd:/1ZUr+/LodAe2Let3amFS29C

a=ice-options:trickle renomination

a=fingerprint:sha-256 EE:15:E8:D6:ED:98:3C:BD:36:C3:C3:A7:98:E8:29:4F:B6:FF:8B:0E:E9:A7:C3:0F:E4:1B:03:A6:1B:CD:81:84

a=setup:actpass

a=mid:video

a=extmap:2 urn:ietf:params:rtp-hdrext:toffset

a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:4 urn:3gpp:video-orientation

a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type

a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing


a=sendrecv

a=rtcp-mux

a=rtcp-rsize

a=rtpmap:96 VP8/90000

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 goog-remb

a=rtcp-fb:96 transport-cc

a=rtpmap:97 rtx/90000

a=fmtp:97 apt=96

a=rtpmap:98 red/90000

a=rtpmap:99 rtx/90000

a=fmtp:99 apt=98

a=rtpmap:100 ulpfec/90000

a=rtpmap:101 H264/90000

a=rtcp-fb:101 ccm fir

a=rtcp-fb:101 nack

a=rtcp-fb:101 nack pli

a=rtcp-fb:101 goog-remb

a=rtcp-fb:101 transport-cc

a=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

a=rtpmap:127 rtx/90000

a=fmtp:127 apt=101

a=ssrc-group:FID 1764423891 3333745010

a=ssrc:1764423891 cname:FBZNwDVqGrEC/n5L

a=ssrc:1764423891 msid:ARDAMS b8a20667-9e18-4db3-a673-518fdf6e61f6

a=ssrc:1764423891 mslabel:ARDAMS

a=ssrc:1764423891 label:b8a20667-9e18-4db3-a673-518fdf6e61f6

a=ssrc:3333745010 cname:FBZNwDVqGrEC/n5L

a=ssrc:3333745010 msid:ARDAMS b8a20667-9e18-4db3-a673-518fdf6e61f6

a=ssrc:3333745010 mslabel:ARDAMS

a=ssrc:3333745010 label:b8a20667-9e18-4db3-a673-518fdf6e61f6
```

then i just tested maxbundle but it's not working:
```
let constraints = defaultPeerConnectionConstraints()
        let config = RTCConfiguration()
        config.iceServers = defaultSTUNServer()
        config.iceTransportPolicy = .all
//        config.bundlePolicy = .maxBundle
        let peerConnection = factory.peerConnection(with: config, constraints: constraints, delegate: self)
        return peerConnection
```

**Comment by crossle** [comment]
I think you can look at the janus webrtc demo config

**Comment by fukemy** [comment]
yeah, im spent 1 day to compare the difference between 2 sdp, then my server talk: " hey, the last server is accept vp8, but new server only accept H264 to do somethings other....), then i think the problem is about codec config, i tried to force the RtcFactory:

```

        let encoderFactory = RTCVideoEncoderFactoryH264()
        let decoderFactory = RTCVideoDecoderFactoryH264()
        factory = RTCPeerConnectionFactory(encoderFactory: encoderFactory, decoderFactory: decoderFactory)
//        factory = RTCPeerConnectionFactory()
```

i think the only way i need to force the current code to H264 then it's will success display in server, may be i need to look more about codec

**Comment by crossle** [comment]
Please make sure the peerconnection config same with janus demo

**Comment by fukemy** [comment]
hi, finally i found problem, because the proxy server not mapped well. that cause my publisher blinding search upd port always failed. now it's working
