### ISSUE TITLE
Create Dynamic room for each user

### ISSUE THREAD

**Issue by saroar** [crossle/janus-gateway-ios#2]
Hello there i am trying to understand how i can create dynamic janus video room as i see you are using janus gateway if you know please help me thanks
i see we are joined always room number 1234 but how we can create dynamic room for each user then destroy that room after live stream will be finished

**Comment by crossle** [comment]
See https://github.com/crossle/janus-gateway-ios/blob/master/janus-gateway-ios/Janus/WebSocketChannel.m#L169

**Comment by antonyjoemathew** [comment]
@saroar any luck ?

**Comment by saroar** [comment]
@antonyjoemathew I have done long time ago but don't remember how I did sorry :(

**Comment by 1395881288** [comment]
1：
https://janus.conf.meetecho.com/janus
Post
{
        "janus" : "create",
        "transaction" : "mytransaction"
}
return
{
    "janus": "success",
    "transaction": "mytransaction",
    "data": {
        "id": 3385826966130456
    }
}

2：
https://janus.conf.meetecho.com/janus/3385826966130456
Post
{
        "janus" : "attach",
        "plugin" : "janus.plugin.videoroom",
        "transaction" : "mytransaction"
}
return
{
    "janus": "success",
    "session_id": 3385826966130456,
    "transaction": "mytransaction",
    "data": {
        "id": 1740222831923566
    }
}
3：
https://janus.conf.meetecho.com/janus/5830902301268682/7798809198085807
post
{
        "janus" : "message",
        "transaction" : "mytransaction",
        "admin_key ":"supersecret",
        "body":{
          "request" : "create",
          "room" : 123456,
          "permanent":true,
          "description" : "lrwqq's room",
          "record":true,
          "rec_dir" : "/opt/janus/share/janus/recordings",
          "publishers" : 100,
          "secret" : ""
        }
}
return
{
    "janus": "success",
    "session_id": 2666539255865885,
    "transaction": "mytransaction",
    "sender": 1660241997046180,
    "plugindata": {
        "plugin": "janus.plugin.videoroom",
        "data": {
            "videoroom": "created",
            "room": 123456,
            "permanent": true
        }
    }
}

now you can user room 123456
