### ISSUE TITLE
joined room but can not get video

### ISSUE THREAD

**Issue by fukemy** [crossle/janus-gateway-ios#3]
Hi. First thanks for your library, it help me much to know about webrtc, now i have a janus web room example, eg: 

![Screen Shot 2019-05-15 at 15 38 49](https://user-images.githubusercontent.com/8202437/57761364-8e84ab80-7727-11e9-845b-895537027981.png)

When i run your demo, it working, connected to room, but can not get video, can you help me? 

Here is log i got:

`
2019-05-15 15:35:12.284366+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "success",
   "transaction": "WE2OjAaZDBKi",
   "data": {
      "id": 4919043633081722
   }
}
2019-05-15 15:35:12.494907+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "B6wphjk5yAYC"
}
2019-05-15 15:35:12.495053+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:35:12.704735+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "success",
   "session_id": 4919043633081722,
   "transaction": "53jcjPxjUviI",
   "data": {
      "id": 5953178423227213
   }
}
2019-05-15 15:35:12.916813+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "YfnaUQMLCXry"
}
2019-05-15 15:35:12.916976+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:35:12.917079+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "event",
   "session_id": 4919043633081722,
   "transaction": "YfnaUQMLCXry",
   "sender": 5953178423227213,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "joined",
         "room": 1234,
         "description": "Demo Room",
         "id": 169079869564182,
         "private_id": 1664189170,
         "publishers": [
            {
               "id": 1718459725868033,
               "display": "fapfap",
               "audio_codec": "opus",
               "video_codec": "vp8",
               "talking": false
            }
         ]
      }
   }
}
2019-05-15 15:36:03.892135+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "success",
   "session_id": 4919043633081722,
   "transaction": "AF6Pp9GWZHnx",
   "data": {
      "id": 62291161532026
   }
}
2019-05-15 15:36:04.106721+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "FgaWYT9VlNtl"
}
2019-05-15 15:36:04.106862+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:36:04.315836+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "5RvPmdtKgL4Y"
}
2019-05-15 15:36:04.316003+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:36:04.317737+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "event",
   "session_id": 4919043633081722,
   "transaction": "5RvPmdtKgL4Y",
   "sender": 62291161532026,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "attached",
         "room": 1234,
         "id": 1718459725868033,
         "display": "fapfap"
      }
   },
   "jsep": {
      "type": "offer",
      "sdp": "v=0\r\no=- 1557909264724503 1 IN IP4 188.213.167.189\r\ns=VideoRoom 1234\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS janus\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 188.213.167.189\r\na=sendonly\r\na=mid:audio\r\na=rtcp-mux\r\na=ice-ufrag:tY3B\r\na=ice-pwd:OdR768nlkPZMj7XeEgQcEK\r\na=ice-options:trickle\r\na=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38\r\na=setup:actpass\r\na=rtpmap:111 opus/48000/2\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=ssrc:961094923 cname:janus\r\na=ssrc:961094923 msid:janus janusa0\r\na=ssrc:961094923 mslabel:janus\r\na=ssrc:961094923 label:janusa0\r\na=candidate:1 1 udp 2013266431 172.22.0.3 39319 typ host\r\na=candidate:2 1 udp 2013266431 172.18.0.2 49857 typ host\r\na=candidate:3 1 udp 2013266431 188.213.167.189 40092 typ host\r\na=end-of-candidates\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97\r\nc=IN IP4 188.213.167.189\r\na=sendonly\r\na=mid:video\r\na=rtcp-mux\r\na=ice-ufrag:tY3B\r\na=ice-pwd:OdR768nlkPZMj7XeEgQcEK\r\na=ice-options:trickle\r\na=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38\r\na=setup:actpass\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=extmap:12 urn:3gpp:video-orientation\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=ssrc-group:FID 3876101341 3879244285\r\na=ssrc:3876101341 cname:janus\r\na=ssrc:3876101341 msid:janus janusv0\r\na=ssrc:3876101341 mslabel:janus\r\na=ssrc:3876101341 label:janusv0\r\na=ssrc:3879244285 cname:janus\r\na=ssrc:3879244285 msid:janus janusv0\r\na=ssrc:3879244285 mslabel:janus\r\na=ssrc:3879244285 label:janusv0\r\na=candidate:1 1 udp 2013266431 172.22.0.3 39319 typ host\r\na=candidate:2 1 udp 2013266431 172.18.0.2 49857 typ host\r\na=candidate:3 1 udp 2013266431 188.213.167.189 40092 typ host\r\na=end-of-candidates\r\n"
   }
}
2019-05-15 15:36:11.820082+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "l14k7KWkooi3"
}
2019-05-15 15:36:11.820295+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:36:41.853248+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "SAQ0wT5AguE9"
}
2019-05-15 15:36:41.853402+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:37:11.820773+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "ZzOkSYIyS932"
}
2019-05-15 15:37:11.820961+0700 janus-gateway-ios[80469:10518067] Just an ack
2019-05-15 15:37:41.827728+0700 janus-gateway-ios[80469:10518067] ====onMessage={
   "janus": "ack",
   "session_id": 4919043633081722,
   "transaction": "PinPq5ytHHEa"
}
2019-05-15 15:37:41.827909+0700 janus-gateway-ios[80469:10518067] Just an ack

`

**Comment by crossle** [comment]
If you set turn server? https://github.com/crossle/janus-gateway-ios/blob/db5460bd998f350c741fcf3800c9adc2eab29c6a/janus-gateway-ios/Janus/ViewController.m#L65

**Comment by fukemy** [comment]
i think RTCPeerConnection delegate not called, even it successuly created

**Comment by fukemy** [comment]
Hi, can you tell me how to get turn server link? I dont know much about it

**Comment by fukemy** [comment]
Hi, after comment code:
`
//    NSMutableArray *iceServers = [NSMutableArray arrayWithObject:[self defaultSTUNServer]];
//    config.iceServers = iceServers;
//    config.iceTransportPolicy = RTCIceTransportPolicyRelay;
`, the video appear

![Screen Shot 2019-05-15 at 15 55 17](https://user-images.githubusercontent.com/8202437/57762521-d9072780-7729-11e9-931f-616028685d54.png)

But it's just my camera send to room, i need get video from room, can you help me about this?

**Comment by crossle** [comment]
Any decode video error?

**Comment by fukemy** [comment]
No. it's working now. Thanks, that's slow internet problem.
