### ISSUE TITLE
Cant see remote user video in room

### ISSUE THREAD

**Issue by haiderkhan87** [crossle/janus-gateway-ios#5]
When I launch the iOS application: Following methods are called.

1.===========Create Session called================
2. =========keep alive called============= (keeps calling via timer)
3.==========Publisher create handle called================
4.==========Publisher join Room called================
5.===========Publisher joined===============
6. ==========Offer Peer Connection============
7.==========Creating Peer Connection===========

Then, Join the room with user “browserTestUser” via Firefox browser, I get the following log in iOS Application. 

====onMessage={
   "janus": "event",
   "session_id": 251445620598646,
   "sender": 4201993931821009,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "event",
         "room": 1234,
         "publishers": [
            {
               "id": 7119049380806702,
               "display": "browserTestUser",
               "audio_codec": "opus",
               "video_codec": "vp8",
               "talking": false
            }
         ]
      }
   }
}
 =========subscriber create handle called=============
 ========subscriber join called==============

2019-11-25 17:53:06.990878+0500 janus-gateway-ios[19462:9706815] ====onMessage={
   "janus": "event",
   "session_id": 251445620598646,
   "transaction": "FfhKoL6dZXFp",
   "sender": 6991255944261373,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "attached",
         "room": 1234,
         "id": 7119049380806702,
         "display": "browserTestUser",
         "warning": "Deprecated use of 'listener' ptype, update to the new 'subscriber' ASAP"
      }
   },
   "jsep": {
      "type": "offer",
      "sdp": "v=0\r\no=- 1574686386683951 1 IN IP4 115.186.191.11\r\ns=VideoRoom 1234\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS janus\r\na=ice-lite\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 115.186.191.11\r\na=sendonly\r\na=mid:audio\r\na=rtcp-mux\r\na=ice-ufrag:6IVN\r\na=ice-pwd:UEom13xFRCfUG7C+qQG3de\r\na=ice-options:trickle\r\na=fingerprint:sha-256 2F:8E:07:FD:20:CC:61:26:78:52:0A:24:54:54:F2:15:9F:45:9A:FD:06:B1:59:33:43:27:2C:8C:E1:98:3F:46\r\na=setup:actpass\r\na=rtpmap:111 opus/48000/2\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=ssrc:2212557319 cname:janus\r\na=ssrc:2212557319 msid:janus janusa0\r\na=ssrc:2212557319 mslabel:janus\r\na=ssrc:2212557319 label:janusa0\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 115.186.191.11\r\na=sendonly\r\na=mid:video\r\na=rtcp-mux\r\na=ice-ufrag:6IVN\r\na=ice-pwd:UEom13xFRCfUG7C+qQG3de\r\na=ice-options:trickle\r\na=fingerprint:sha-256 2F:8E:07:FD:20:CC:61:26:78:52:0A:24:54:54:F2:15:9F:45:9A:FD:06:B1:59:33:43:27:2C:8C:E1:98:3F:46\r\na=setup:actpass\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=ssrc:1803816776 cname:janus\r\na=ssrc:1803816776 msid:janus janusv0\r\na=ssrc:1803816776 mslabel:janus\r\na=ssrc:1803816776 label:janusv0\r\n"
   }
}
2019-11-25 17:53:06.992785+0500 janus-gateway-ios[19462:9706815] ==========Creating Peer Connection===========
2019-11-25 17:53:06.994929+0500 janus-gateway-ios[19462:9706815] ==========Subscriber set remote description======

The problem is, I cant see remote user video in the room.
Do I need to setup Ice server/STUN/Turn etc.
Any help will be apprecialble.

Best regards.

**Comment by crossle** [comment]
Yes, you need setup TURN server

**Comment by haiderkhan87** [comment]
Thank you for quick response. I have used google STUN server.
Now I am facing following error.

"
2019-11-26 14:01:49.247759+0500 janus-gateway-ios[19945:10002717] Metal API Validation Enabled
2019-11-26 14:01:50.283263+0500 janus-gateway-ios[19945:10002717] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x283bbcaa0> to GL_RENDERBUFFER 1
2019-11-26 14:01:50.283512+0500 janus-gateway-ios[19945:10002717] Failed to make complete framebuffer object 8cd6
"

And sometimes, a black screen of remote user appears.

**Comment by crossle** [comment]
If you STUN server, you should change the relay https://github.com/crossle/janus-gateway-ios/blob/db5460bd998f350c741fcf3800c9adc2eab29c6a/janus-gateway-ios/Janus/ViewController.m#L77

**Comment by haiderkhan87** [comment]
Thank you so much. Its working now.
