### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by nikhil191090** [crossle/janus-gateway-ios#8]
Hello, Thank you for this perfect demo. can you please create this demo using swift language, that will be really helpful

**Comment by nikhil191090** [comment]
Hello @crossle , I converted the code in swift, everything converted successfully, but i am facing one issue that remote video view showing a black screen, please help I am kind of stuck here.

**Comment by crossle** [comment]
https://github.com/crossle/janus-gateway-ios/issues/5

**Comment by nikhil191090** [comment]
Hello @crossle Thank you for your reply. i am adding code that i created 

 func defaultSTUNServer() -> RTCIceServer? {
        let array = ["turn:xxxxx"]
        return RTCIceServer(urlStrings: array, username: "xxx", credential: "xxx")
    }

    func createPeerConnection() -> RTCPeerConnection? {
        let constraints = defaultPeerConnectionConstraints()
        let config = RTCConfiguration()
        config.iceServers = [defaultSTUNServer()!]
        config.iceTransportPolicy = RTCIceTransportPolicy.relay
        let peerConnection = factory!.peerConnection(with: config, constraints: constraints!, delegate: self)
        return peerConnection
    }


still getting same issue

**Comment by nikhil191090** [comment]
@crossle 
![IMG_9102](https://user-images.githubusercontent.com/13807014/73334402-9b840380-4292-11ea-858c-03f3a11c77c3.PNG)

**Comment by amirali-asvadi** [comment]
> Hello @crossle , I converted the code in swift, everything converted successfully, but i am facing one issue that remote video view showing a black screen, please help I am kind of stuck here.

Hi
I converted it to swift, contact me on  amiraliasvde@gmail.com for source code!

**Comment by lygon55555** [comment]
@nikhil191090 Hi, I'm trying to convert the code in Swift
but I'm getting trouble since I'm not good at Objective-C.
If you are ok, can you send me your Swift code?

**Comment by nikhil191090** [comment]
@lygon55555 actually i don't have code right now with me , so cant share , I am sorry

**Comment by lygon55555** [comment]
@nikhil191090 oh, I see. Thanks for the reply.
